apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
  namespace: mern
type: Opaque
stringData:
  MONGO_USERNAME: root
  MONGO_PASSWORD: changeme-in-production
  ATLAS_URI: mongodb://root:changeme-in-production@mongodb:27017/sample_training?authSource=admin
